//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EDIEntities : DbContext
    {
        public EDIEntities()
            : base("name=EDIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<company_master> company_master { get; set; }
        public virtual DbSet<edi_format_master> edi_format_master { get; set; }
        public virtual DbSet<menu_master> menu_master { get; set; }
        public virtual DbSet<package_master> package_master { get; set; }
        public virtual DbSet<role_master> role_master { get; set; }
        public virtual DbSet<sub_menu> sub_menu { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<transaction_rejected> transaction_rejected { get; set; }
        public virtual DbSet<transaction_sent> transaction_sent { get; set; }
        public virtual DbSet<user_master> user_master { get; set; }
        public virtual DbSet<erp_master> erp_master { get; set; }
        public virtual DbSet<subscription_master> subscription_master { get; set; }
    
        public virtual ObjectResult<SPO_getAllMenuByUserID_Result> SPO_getAllMenuByUserID(Nullable<int> userID, string userName)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPO_getAllMenuByUserID_Result>("SPO_getAllMenuByUserID", userIDParameter, userNameParameter);
        }
    }
}
