//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_sent
    {
        public int t_id { get; set; }
        public Nullable<int> c_id { get; set; }
        public Nullable<int> edi_code { get; set; }
        public string sent { get; set; }
        public string received { get; set; }
        public Nullable<int> t_partner_id { get; set; }
        public string doc_type { get; set; }
        public Nullable<int> doc_code { get; set; }
        public Nullable<int> a_doc_code { get; set; }
        public Nullable<int> store_no { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> date_send { get; set; }
        public Nullable<System.DateTime> d_acnoledgment { get; set; }
    
        public virtual company_master company_master { get; set; }
    }
}
