//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C810_Detail
    {
        public int DetailKey { get; set; }
        public Nullable<int> HeaderKey { get; set; }
        public string IT102_QtyInvoiced { get; set; }
        public string IT103_Unit { get; set; }
        public string IT104_UnitPrice { get; set; }
        public string IT107_PetSmartArticleNo { get; set; }
        public string IT108_ProductServiceIdQlfr { get; set; }
        public string IT109_ProductServiceId { get; set; }
        public string SAC02_AllowanceCode { get; set; }
        public string SAC05_AllowanceAmount { get; set; }
        public string SAC02_ChargeCode { get; set; }
        public string SAC05_ChargeAmount { get; set; }
    
        public virtual C810_Header C810_Header { get; set; }
    }
}
