//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C850_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C850_Header()
        {
            this.C850_Detail = new HashSet<C850_Detail>();
        }
    
        public int HeaderKey { get; set; }
        public Nullable<int> FunctionalGroupKey { get; set; }
        public string FGKeySave { get; set; }
        public string ST01_TranSetIdfrCode { get; set; }
        public string ST02_TranSetControlNo { get; set; }
        public string BEG01_TransactionSetPurposeCode { get; set; }
        public string BEG02_PurchaseOrderTypeCode { get; set; }
        public string BEG03_PurchaseOrderNumber { get; set; }
        public string BEG05_PODate { get; set; }
        public string CUR02_CurrencyCode { get; set; }
        public string REF02_FreeFormText { get; set; }
        public string REF02_InternalVendorNo { get; set; }
        public string REF02_ProductGroup { get; set; }
        public string PER02_ContactPersonName { get; set; }
        public string DTM02_DeliveryRequestedDate { get; set; }
        public string DTM02_RequestedPickupDate { get; set; }
        public string N104_ShipFromID { get; set; }
        public string N401_ShipFromCity { get; set; }
        public string N402_ShipFromState { get; set; }
        public string N403_ShipFromPostalCode { get; set; }
        public string N404_ShipFromCountryCode { get; set; }
        public string N104_ShipToID { get; set; }
        public string N401_ShipToCity { get; set; }
        public string N402_ShipToState { get; set; }
        public string N403_ShipToPostalCode { get; set; }
        public string N404_ShipToCountryCode { get; set; }
        public string CTT01_NumberOfPO1Segments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C850_Detail> C850_Detail { get; set; }
    }
}
