//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C852_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C852_Detail()
        {
            this.C852_ProdActivity = new HashSet<C852_ProdActivity>();
        }
    
        public int DetailKey { get; set; }
        public Nullable<int> HeaderKey { get; set; }
        public string LIN03_GTIN_UCC_Code { get; set; }
        public string LIN05_BuyerItemNo { get; set; }
        public string LIN07_VendorItemNo { get; set; }
        public string CTP02_PriceCode { get; set; }
        public string CTP03_UnitPrice { get; set; }
        public string PO406_WeightPerPack { get; set; }
        public string PO407_Unit { get; set; }
    
        public virtual C852_Header C852_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C852_ProdActivity> C852_ProdActivity { get; set; }
    }
}
