//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C856_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C856_Header()
        {
            this.C856_Shipment = new HashSet<C856_Shipment>();
        }
    
        public int HeaderKey { get; set; }
        public Nullable<int> FunctionalGroupKey { get; set; }
        public string ST01_TranSetIdfrCode { get; set; }
        public string ST02_TranSetControlNo { get; set; }
        public string BSN01_TranSetPurposeCode { get; set; }
        public string BSN02_ShipmentId { get; set; }
        public string BSN03_TranSetDate { get; set; }
        public string BSN04_TranSetTime { get; set; }
        public string BSN05_HierarchicalStructureCode { get; set; }
        public string CTT01_NumberOfLineItems { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C856_Shipment> C856_Shipment { get; set; }
    }
}
