//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C856_Item
    {
        public int ItemKey { get; set; }
        public Nullable<int> PackKey { get; set; }
        public string LIN02_TypeSourceCode { get; set; }
        public string LIN03_ProductServiceId { get; set; }
        public string LIN05_BuyerItemNo { get; set; }
        public string LIN07_GTIN_EAN_UCC { get; set; }
        public string LIN09_LotNo { get; set; }
        public string SN102_UnitsShipped { get; set; }
        public string SN103_Unit { get; set; }
        public string SLN01_AssignedId { get; set; }
        public string SLN03_RelationshipCode { get; set; }
        public string SLN09_TypeSourceCode { get; set; }
        public string SLN10_ProductServiceId { get; set; }
        public string DTM02_ExpirationDate { get; set; }
    
        public virtual C856_Pack C856_Pack { get; set; }
    }
}
