//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDIFile
    {
        public int RejectedFileID { get; set; }
        public string fileNames { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string EdiFileTranSetNo { get; set; }
        public string CreatedDateTime { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
