//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterchangeInbound
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InterchangeInbound()
        {
            this.FunctionalGroupInbounds = new HashSet<FunctionalGroupInbound>();
        }
    
        public int InterchangeKey { get; set; }
        public string ISA01_AuthorizationInfoQlfr { get; set; }
        public string ISA02_AuthorizationInfo { get; set; }
        public string ISA03_SecurityInfoQlfr { get; set; }
        public string ISA04_SecurityInfo { get; set; }
        public string ISA05_SenderIdQlfr { get; set; }
        public string ISA06_SenderId { get; set; }
        public string ISA07_ReceiverIdQlfr { get; set; }
        public string ISA08_ReceiverId { get; set; }
        public string ISA09_Date { get; set; }
        public string ISA10_Time { get; set; }
        public string ISA11_RepetitionSeparator { get; set; }
        public string ISA12_ControlVersionNumber { get; set; }
        public string ISA13_ControlNumber { get; set; }
        public string ISA14_AcknowledgmentRequested { get; set; }
        public string ISA15_UsageIndicator { get; set; }
        public string ISA16_ComponentElementSeparator { get; set; }
        public string IEA01_NoOfIncludedFuncGroups { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FunctionalGroupInbound> FunctionalGroupInbounds { get; set; }
    }
}
