//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_master
    {
        public menu_master()
        {
            this.sub_menu = new HashSet<sub_menu>();
        }
    
        public int m_id { get; set; }
        public string m_name { get; set; }
    
        public virtual ICollection<sub_menu> sub_menu { get; set; }
    }
}
