//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_master
    {
        public package_master()
        {
            this.company_master = new HashSet<company_master>();
            this.subscription_master = new HashSet<subscription_master>();
        }
    
        public int p_id { get; set; }
        public string p_name { get; set; }
        public string p_duration { get; set; }
        public string price { get; set; }
        public string discount { get; set; }
    
        public virtual ICollection<company_master> company_master { get; set; }
        public virtual ICollection<subscription_master> subscription_master { get; set; }
    }
}
