//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C810_Header
    {
        public C810_Header()
        {
            this.C810_Detail = new HashSet<C810_Detail>();
        }
    
        public int HeaderKey { get; set; }
        public Nullable<int> FunctionalGroupKey { get; set; }
        public string ST01_TranSetIdfrCode { get; set; }
        public string ST02_TranSetControlNo { get; set; }
        public string BIG01_InvoiceDate { get; set; }
        public string BIG02_InvoiceNo { get; set; }
        public string BIG04_PurchaseOrderNo { get; set; }
        public string REF02_PetSmartVendorNo { get; set; }
        public string N104_PetSmartSiteNo { get; set; }
        public string ITD03_TermsDiscountPercent { get; set; }
        public string ITD05_TermsDiscountDaysDue { get; set; }
        public string ITD07_TermsNetDays { get; set; }
        public string ITD12_Description { get; set; }
        public string TDS01_InvoiceTotalAmount { get; set; }
        public string TXI02_HarmonizedSalesTax { get; set; }
        public string TXI02_GoodsServicesTax { get; set; }
        public string TXI02_StateTax { get; set; }
        public string SAC02_TotalAllowanceCode { get; set; }
        public string SAC05_TotalAllowanceAmount { get; set; }
        public string SAC02_TotalChargeCode { get; set; }
        public string SAC05_TotalChargeAmount { get; set; }
        public string CTT01_NumberOfLineItems { get; set; }
    
        public virtual ICollection<C810_Detail> C810_Detail { get; set; }
    }
}
