//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C852_Header
    {
        public C852_Header()
        {
            this.C852_Detail = new HashSet<C852_Detail>();
        }
    
        public int HeaderKey { get; set; }
        public Nullable<int> FunctionalGroupKey { get; set; }
        public string ST01_TranSetIdfrCode { get; set; }
        public string ST02_TranSetControlNo { get; set; }
        public string XQ02_ReportingDate { get; set; }
        public string XQ03_ReportingEndDate { get; set; }
        public string N902_InternalVendorNo { get; set; }
        public string N903_FreeFormDesc { get; set; }
        public string CTT01_NumberOfLineItems { get; set; }
    
        public virtual ICollection<C852_Detail> C852_Detail { get; set; }
    }
}
