//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_setup
    {
        public string item__id { get; set; }
        public string item_translation { get; set; }
        public string Upc__ { get; set; }
        public string Vendor_Part_id { get; set; }
        public string Buyer_part { get; set; }
        public string Description { get; set; }
        public string UOM { get; set; }
        public string Price { get; set; }
        public string Price_basis { get; set; }
        public string C__of_Inner_packs { get; set; }
        public string C__of_unit_in_cartoons { get; set; }
        public string Max__ { get; set; }
        public string ucc_128__ { get; set; }
        public string Vendor_Part__ { get; set; }
        public string Gtin__ { get; set; }
        public string Kmart_Code { get; set; }
        public string Unique_product__ { get; set; }
        public string Package_Indicator { get; set; }
        public string Ucc_Company_prifix { get; set; }
        public string Qty_Shipped { get; set; }
        public string Pack_Size { get; set; }
        public string weight { get; set; }
        public string length { get; set; }
        public string width { get; set; }
        public string Height { get; set; }
        public string Manufacturer_Part { get; set; }
        public string Ean { get; set; }
        public string income { get; set; }
        public string expence { get; set; }
        public string Cost_of_Sales { get; set; }
        public string id { get; set; }
    
        public virtual tradingPartnerSetup tradingPartnerSetup { get; set; }
    }
}
