//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_master
    {
        public role_master()
        {
            this.MenuRoleMappings = new HashSet<MenuRoleMapping>();
            this.user_master = new HashSet<user_master>();
        }
    
        public int role_id { get; set; }
        public string roll_name { get; set; }
        public int Role_Id2 { get; set; }
    
        public virtual ICollection<MenuRoleMapping> MenuRoleMappings { get; set; }
        public virtual ICollection<user_master> user_master { get; set; }
    }
}
