//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.EDIFiles = new HashSet<EDIFile>();
        }
    
        public int StatusID { get; set; }
        public string StatusCode { get; set; }
        public string StatusDesc { get; set; }
    
        public virtual ICollection<EDIFile> EDIFiles { get; set; }
    }
}
