//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_rejected
    {
        public string t_id { get; set; }
        public string c_id { get; set; }
        public string edi_code { get; set; }
        public string sent { get; set; }
        public string received { get; set; }
        public string t_partner_id { get; set; }
        public string doc_type { get; set; }
        public string doc_code { get; set; }
        public string a_doc_code { get; set; }
        public string store_no { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> date_rejected { get; set; }
        public Nullable<System.DateTime> d_acnoledgment { get; set; }
    
        public virtual company_master company_master { get; set; }
    }
}
