//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public string company { get; set; }
        public string trading_partner { get; set; }
        public string document { get; set; }
        public string document_number { get; set; }
        public string Alt_document { get; set; }
        public string store_number { get; set; }
        public string amount { get; set; }
        public Nullable<System.DateTime> date_received { get; set; }
        public Nullable<System.DateTime> date_ack { get; set; }
        public string t_id { get; set; }
        public string c_id { get; set; }
        public string doc_id { get; set; }
        public string tp_id { get; set; }
    
        public virtual company_master company_master { get; set; }
        public virtual docu_type docu_type { get; set; }
        public virtual tradingPartnerSetup tradingPartnerSetup { get; set; }
    }
}
