//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_master
    {
        public int user_id { get; set; }
        public string u_first_name { get; set; }
        public string u_last_name { get; set; }
        public string c_id { get; set; }
        public Nullable<int> role_id { get; set; }
        public string UserName { get; set; }
        public int phone_no { get; set; }
        public string email_id { get; set; }
        public string Password { get; set; }
    
        public virtual company_master company_master { get; set; }
        public virtual role_master role_master { get; set; }
    }
}
