//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_menu
    {
        public int sub_m_id { get; set; }
        public string Submenu_name { get; set; }
        public Nullable<int> m_id { get; set; }
    
        public virtual menu_master menu_master { get; set; }
    }
}
