//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C860_Detail
    {
        public int DetailKey { get; set; }
        public Nullable<int> HeaderKey { get; set; }
        public string POC02_ChangeTypeCode { get; set; }
        public string POC06_UnitPrice { get; set; }
        public string POC09_GTIN_EAN_UCC { get; set; }
        public string POC09_GTIN_UCC { get; set; }
        public string POC11_BuyerItemNo { get; set; }
        public string POC13_VendorItemNo { get; set; }
        public string POC15_CommodityGroupingID { get; set; }
        public string POC17_CaseID { get; set; }
        public string PO406_WeightPerPack { get; set; }
        public string PO407_WeightUnit { get; set; }
        public string PO408_VolumePerPack { get; set; }
        public string PO409_VolumeUnit { get; set; }
        public string QTY02_QuantityAdjusted { get; set; }
        public string QTY03_01_Unit { get; set; }
    
        public virtual C860_Header C860_Header { get; set; }
    }
}
