//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class docu_type_sub
    {
        public string d_id { get; set; }
        public string d_num { get; set; }
        public string alt_number { get; set; }
        public string d_subid { get; set; }
    
        public virtual docu_type docu_type { get; set; }
    }
}
