//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class edi_format_master
    {
        public string edi_code { get; set; }
        public string edi_type { get; set; }
        public string c_name { get; set; }
        public string edi_foramt { get; set; }
    }
}
