//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionalGroupOutbound
    {
        public int FunctionalGroupKey { get; set; }
        public int InterchangeKey { get; set; }
        public string GS01_FunctionalIdfrCode { get; set; }
        public string GS02_SendersCode { get; set; }
        public string GS03_ReceiversCode { get; set; }
        public string GS04_Date { get; set; }
        public string GS05_Time { get; set; }
        public string GS06_GroupControlNumber { get; set; }
        public string GS07_ResponsibleAgencyCode { get; set; }
        public string GS08_VersionReleaseCode { get; set; }
        public string GE01_NoOfTranSetsIncluded { get; set; }
    
        public virtual InterchangeOutbound InterchangeOutbound { get; set; }
    }
}
