//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuRoleMapping
    {
        public string Menu_Id { get; set; }
        public Nullable<int> Sub_Menu_Id { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<int> PermissionTypeID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string MenuRoleMappingID { get; set; }
    
        public virtual menu_master menu_master { get; set; }
        public virtual PermissionType PermissionType { get; set; }
        public virtual role_master role_master { get; set; }
        public virtual sub_menu sub_menu { get; set; }
    }
}
