//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription_master
    {
        public string c_name { get; set; }
        public int p_id { get; set; }
        public string p_name { get; set; }
    
        public virtual package_master package_master { get; set; }
    }
}
